### ISSUE TITLE
error occurred while trying to install Winter CMS via Web Installer

### ISSUE THREAD

**Issue by Dione-stack** [wintercms/web-installer#11]
I get this error at the end of the installation and i'm not able to fix it

Sorry, but an error has occurred while trying to install Winter CMS.
DirectoryIterator::__construct(C:\Windows\Temp\.composer,C:\Windows\Temp\.composer): Access is denied. (code: 5)

I followed the instructions and I have given full control to all subfolders and files, please help

**Comment by bennothommo** [comment]
@Dione-stack I have pushed a potential fix for this - it appears to be a Windows pathing issue.

I will release a new beta release of the Web installer shortly.

**Comment by Dione-stack** [comment]
Let me know when the Web installer is updated so i can retry, and thank you

**Comment by bennothommo** [comment]
@Dione-stack could you try the fix directly? There's a couple of things I want to finalise before doing another release.

You can simply take the following code change (https://github.com/wintercms/web-installer/commit/9c82259b016115118760e578d8e44e422a29e27a) and replace the red highlighted lines with the green highlighted lines in the `install/api/src/Api.php` file of the installer files.

**Comment by Dione-stack** [comment]
I updated the Api.php file as you suggested, but after running the installation, the same error occurred

**Comment by Dione-stack** [comment]
Actually it's not the same error...

previous error:
DirectoryIterator::__construct(C:\Windows\Temp.composer,C:\Windows\Temp.composer): Access is denied. (code: 5)
current error:
DirectoryIterator::__construct(C:\Windows\Temp\.composer,C:\Windows\Temp\.composer): Access is denied. (code: 5)

**Comment by bennothommo** [comment]
@Dione-stack that looks like the same error to me? :P

I haven't got a Windows box currently to test it on, but the path it's showing looks strange - the path should be `C:\Windows\Temp\.composer`, not `C:\Windows\Temp.composer`.

**Comment by Dione-stack** [comment]
yes it says C:\Windows\Temp\.composer instead of C:\Windows\Temp.composer in the current error

**Comment by bennothommo** [comment]
@Dione-stack apologies, but am I missing something? Those are the same paths.

**Comment by Dione-stack** [comment]
trust me i don't know why either, github changes it when i post it, weird

**Comment by bennothommo** [comment]
@Dione-stack no probs - could you screenshot it for us?

**Comment by Dione-stack** [comment]
[https://www.mediafire.com/view/m69qsa4ffpqcw6h](here)

**Comment by Dione-stack** [comment]
[screenshot](https://www.mediafire.com/view/m69qsa4ffpqcw6h)

**Comment by bennothommo** [comment]
@Dione-stack thanks for that, so it is doing the correct path but it's still blocking you due to permissions. I think the fix here is to set up the Composer cache within the same path we are installing to, since you would've already fixed the permissions there. I'll try look into that shortly.

**Comment by Dione-stack** [comment]
Looks like it's going to take some time, i will check back tomorrow and see if you found a solution

**Comment by Dione-stack** [comment]
@bennothommo Just to make it clear, there wasn't a previous and current error, it's the same error, simply i just don't know how to use github, i didn't know i had to use 'insert code' tool to be able to display a path correctly

with 'insert code' tool:
`C:\Windows\Temp\.composer`
without 'insert code' tool:
C:\Windows\Temp\.composer

Please delete this awkward and confusing issue, i will just wait for the next update hopefully then the error will disappear

**Comment by bennothommo** [comment]
@Dione-stack no worries, I'll close this for now with the message that it should hopefully be fixed in the next release. If the next release still exhibits issues, please feel free to re-open and let us know.
