### ISSUE TITLE
Webinstaller error "Unable to determine dependencies..."

### ISSUE THREAD

**Issue by ovillani** [wintercms/web-installer#13]
By trying to install WN on a shared hosting server the process ends up in an error message saying "Unable to determine dependencies for Winter CMS. Your composer.json file is invalid." All checks before are fine and the error happens as soon as the install process says "installing dependencies". Error occurs by using MySQL as well as SQlite. Occurs too when all files are set to 777.

**Comment by mjauvin** [comment]
can you attach the screenshot you had on discord?

**Comment by ovillani** [comment]
Here it is from another try, this time trying SQLite as DB.

![Clipboard02](https://user-images.githubusercontent.com/6983432/123513589-49fdc500-d68e-11eb-9b22-18b20a7f4685.jpg)

**Comment by bennothommo** [comment]
@ovillani could you provide a couple of details:

- Which PHP version are you using?
- Which operating system are you using?
- Is there a `.wintercms/composer.json` file inside your install directory? If so, are you able to provide us with the contents of this file?

**Comment by ovillani** [comment]
sure,
- php 7.4.18
- debian 4.19.181

/.wintercms/composer.json is
<pre>
{
    "name": "wintercms/winter",
    "description": "Free, open-source, self-hosted CMS platform based on the Laravel PHP Framework. Originally known as October CMS.",
    "homepage": "https://wintercms.com",
    "type": "project",
    "keywords": ["winter", "cms", "wintercms", "laravel", "cmf"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Luke Towers",
            "email": "wintercms@luketowers.ca",
            "role": "Lead Maintainer"
        }
    ],
    "support": {
        "issues": "https://github.com/wintercms/winter/issues",
        "docs": "https://wintercms.github.io/docs/",
        "discord": "https://discord.gg/D5MFSPH6Ux",
        "source": "https://github.com/wintercms/winter"
    },
    "require": {
        "php": ">=7.2.9",
        "winter/storm": "~1.1.2",
        "winter/wn-system-module": "~1.1.2",
        "winter/wn-backend-module": "~1.1.2",
        "winter/wn-cms-module": "~1.1.2",
        "laravel/framework": "~6.0",
        "wikimedia/composer-merge-plugin": "~2.0.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.4|^9.3.3",
        "mockery/mockery": "~1.3.3|^1.4.2",
        "fakerphp/faker": "~1.9",
        "squizlabs/php_codesniffer": "3.*",
        "php-parallel-lint/php-parallel-lint": "^1.0",
        "dms/phpunit-arraysubset-asserts": "^0.1.0|^0.2.1"
    },
    "autoload-dev": {
        "classmap": [
            "tests/concerns/InteractsWithAuthentication.php",
            "tests/fixtures/backend/models/UserFixture.php",
            "tests/TestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate",
            "php artisan package:discover"
        ],
        "post-update-cmd": [
            "php artisan winter:version",
            "php artisan package:discover"
        ],
        "test": [
            "phpunit --stop-on-failure"
        ],
        "lint": [
            "parallel-lint --exclude vendor --exclude storage --exclude tests/fixtures/plugins/testvendor/goto/Plugin.php ."
        ],
        "sniff": [
            "phpcs --colors -nq --report=\"full\" --extensions=\"php\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}
</pre>

**Comment by bennothommo** [comment]
@ovillani thanks - yeah that `composer.json` seems fine to me.

At this point in time, the "Your composer.json file is invalid" is a rather vague error which could mean a couple of things, but I'm working towards a new release of the installer that will have logging, which should give more context. In the mean time, you might have to do a Composer install for now.

**Comment by ovillani** [comment]
Indeed, but this is the built in message ;) 
So I looked for some more detailed info. What I found meanwhile:

The err seems to occurs in the **install\api\src\Api.php**   _function postInstallDependencies()_ at line 345
 <pre>
            $install = $composer->install(true);
</pre>

the previous line: 
            $composer->setHomeDir($tmpHomeDir);
seems to be executed fine. But nevertheless the $tmpHomeDir is prompted to be (in my case) 
/data/web/XXXXXXXX/phptmp/.composer (the X are for my shared host dir)
that's a little weird, cause I can't find this directory in my root
Digging deeper in this currently.

**Comment by bennothommo** [comment]
@ovillani Ah, looks like you're affected by the same issue that was reported here: https://github.com/wintercms/web-installer/issues/11. The next release should hopefully resolve this.

> BTW: There is/was an option in OC webinstaller to set access rights to 775 or even 777 for some problems. Can't find this in the WN web installer.

Yes, I opted not to include this because it was a potentially risky setting if done incorrectly. We're using sensible defaults in the config, and it can still be modified that way if people wish.

**Comment by ovillani** [comment]
Definitely understand your concerns about security. On the other hand, if these rights are granted only during the installation process, the risk is limited.
I'll try an (old) OC installation on this server with limited & extended rights today and will forward the results. Just to encircle the problem.

**Comment by ovillani** [comment]
Ok, tried OC installation to compare with file permission 644 and folder permission 755. Works, but the usual ErrorException: Not finding services.php by first login attempt, 2nd login is ok - a problem reported repeatedly by some user at OC, but never was solved.
May ba a similar problem?

**Comment by Turlin666** [comment]
Hello
Same error and error screen, trying with:
- PHP 7.4.20 & 8.0.7
- CentOS 7.9.2009 ->  Plesk Obsidian v18.0.36 (Last updates and composer installed)
- MariaDB 5.5.68
-Same .wintercms/composer.json that @ovillani

**Comment by bennothommo** [comment]
@ovillani @Turlin666 the next release will be coming out in the next few days which should hopefully resolve this. Even if it doesn't, it will have logging so we hopefully get some more context as to what is occurring.

**Comment by ovillani** [comment]
Great! Will give it a try immediately then and keep you informed.

**Comment by Turlin666** [comment]
Thanks !!

**Comment by ovillani** [comment]
@bennothommo Thanks a lot for keeping me informed! I can give it a try this weekend and report the results then.

**Comment by Turlin666** [comment]
Same error for me again...
[install.log](https://github.com/wintercms/web-installer/files/7001497/install.log)

**Comment by bennothommo** [comment]
@Turlin666 thanks for letting me know.

We believe we've worked out the cause. The issue is generally related to shared hosts blocking access to the `proc_open` method which is used for running external Composer actions, such as bringing in dependencies through Git, and extracting packages. This may also manifest if your shared hosting provider does not provide the `pcntl` PHP extension.

Unfortunately, it's likely that your shared hosts may never allow access to these functions, as a lot of them block these to prevent people running command-line tools on their hosting. You can try and get in contact with them to ask if they can enable it, but it wouldn't be surprising if they won't.

We're currently investigating ways around this, but all options so far will take a little extra time to implement, so at this stage, the only option is to try and contact your hosting provider.

**Comment by Turlin666** [comment]
@bennothommo Anyway, thanks for the great job and the support, I have all the access to the server and I will try to work on this way

**Comment by bennothommo** [comment]
@Turlin666 not a problem. If you have full access, are you able to let me know if the `proc_open` command is available for you (ie. it's not in the `disable_functions` configuration option in the PHP config), and that the `pcntl` extension is enabled? If both those points are true, then the issue you're encountering is somewhere else.

**Comment by Turlin666** [comment]
This is my 
`disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,`

On another server that previously failed (width plesk, multidomain), now the installer works correctly without changes

**Comment by bennothommo** [comment]
@Turlin666 looks like `pcntl` is disabled in that config above, by way of disabling all its functions.

**Comment by Turlin666** [comment]
@bennothommo Leaving the `disable_functions` line empty work for me, Thanks a lot

**Comment by xitara** [comment]
(I'm Manuel B. in discord)
In my case, installing and enabling pcntl hast no effect

These are my disabled functions in php.ini:

show_source, 
highlight_file, 
apache_child_terminate, 
apache_get_modules, 
apache_note, 
apache_setenv, 
virtual, 
dl, 
disk_total_space, 
posix_getpwnam, 
posix_getpwuid, 
posix_mkfifo, 
posix_mknod, 
posix_setpgid, 
posix_setsid, 
posix_setuid, 
posix_uname, 
proc_nice, 
openlog, 
syslog, 
pfsockopen

**Comment by LukeTowers** [comment]
@xitara can you provide your install.log file?
