### ISSUE TITLE
Post-install additions to .htaccess

### ISSUE THREAD

**Issue by joho1968** [wintercms/web-installer#28]
Just my two cents:

Add a re-write rule to .htaccess in your post-installation code that re-directs /install.html and /install/ to the starting page.

**Comment by bennothommo** [comment]
Sorry for the delay in responding to this @joho1968.

The installer removes the `install.html` file and `install` directory at the end of the installation - see https://github.com/wintercms/web-installer/blob/main/public/install/api/src/Api.php#L667-L676, so a rewrite rule wouldn't be needed. I don't think it would be a good idea to have an arbitrary rule in the `.htaccess` for this, especially on the (admittedly unlikely) chance that someone actually wants a page path in their site to be `/install/`, [like we do!](https://wintercms.com/install)
