### ISSUE TITLE
[Fresh install] Checks step

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/web-installer#32]
Hi,
I try to install WinterCMS on Ubuntu with the web installer but I can't validate step 2 : the checks step.
I join you a screenshoot
![Capture d’écran du 2023-12-12 14-21-18](https://github.com/wintercms/web-installer/assets/17120690/61667b9c-96ce-4d7d-a583-5be36f5ad6f2)
My OS : Ubuntu 22.04
PHP : 8.0.30
MariaDB : 10.6.12
Apache : 2.4.52
Thanks

**Comment by LukeTowers** [comment]
Which version of PHP is configured for the vhost you're running the installer under? The default CLI version will most likely be different from the configured PHP version for a webhost.

**Comment by m-paniez9292** [comment]
Re,
Ok, it's my fault.
I change the PHP version by `update-alternatives --config php` but, as say Luke, it's only for CLI version.
We must change the Apache extension manually by :
```
a2dismode php7.4
a2enmod php8.0
```
Thanks
