### ISSUE TITLE
php.exe.globals blocked by host [SOLVED]

### ISSUE THREAD

**Issue by bishopm** [wintercms/web-installer#8]
Keen to try out the web installer but my shared host blocked the upload of the install.zip file with the following message:

> The file you uploaded, install.zip, contains a virus so the upload was canceled: 
{HEX}php.exe.globals.418.UNOFFICIAL FOUND

**Comment by bennothommo** [comment]
@bishopm this is most certainly a false positive. I've seen this same "virus" reported on many other PHP projects such as Drupal, SuiteCRM, and others.

If you can, you should disable the virus scan for this file.

Is there any indication on which file inside the .zip file it believes is a virus?

**Comment by mjauvin** [comment]
Also, try uploading with FTP or sftp maybe?

**Comment by bishopm** [comment]
I couldn't pick up which file was triggering the alert, but was able to install successfully by uploading via FTP. Thanks for the help

**Comment by bennothommo** [comment]
@bishopm good to hear!
