### ISSUE TITLE
Allow to change the database charset/collation config

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/web-installer#9]
When using PostgreSQL, the default charset is `utf8` and not `utf8mb4`, this cause the database connection to be unable to run on PostgreSQL installation.

[This laracast thread](https://laracasts.com/discuss/channels/laravel/migration-error-on-heroku-productionerror-sqlstate22023-invalid-parameter-value-7-error-invalid-value-for-parameter-client-encoding-utf8mb4?page=1) and [this SO thread](https://stackoverflow.com/questions/52338761/symfony-4-postgres-invalid-value-for-parameter-client-encoding-utf8mb4) are related and solved my problem (I confirmed that by modifying the charset into the core code).

I'd like to help on this one but I'm not sure how it should be handled:
- Warn the user that he is forced to create an utf8mb4 database?
- Display a list of possible charset/collation?
- Display a basic input text pre-filled with `utf8`?

**Comment by mjauvin** [comment]
Ok, so what you *actually* mean is that currently, the installer uses "utf8mb4" but SHOULD be using "utf8" as the charset/collation.

**Comment by RomainMazB** [comment]
Yes, at least for PostgreSQL database.
I've looked at both laravel's and winter's default database config, and it's already like I said:
- [MySQL defaults to utf8_mb4](https://github.com/wintercms/winter/blob/develop/config/database.php#L65)
- [PostgreSQL defaults to utf8](https://github.com/wintercms/winter/blob/develop/config/database.php#L81)

I guess the reason is the same. I've made a PR to fix that would fit for 99% use cases. The one percent is for the guy out there who is using a custom charset because it want this installer to fails 👀 .

**Comment by bennothommo** [comment]
Fixed by #10.
